---
version: "3.8"
services:
  socket:
    image: "nautobot-chatops/nautobot:${NAUTOBOT_VER}-py${PYTHON_VER}"
    env_file:
      - "development.env"
      - "creds.env"
    tty: true
    entrypoint: "nautobot-server start_slack_socket"
    depends_on:
      - "nautobot"
    healthcheck:
      disable: true
    volumes:
      - "./nautobot_config.py:/opt/nautobot/nautobot_config.py"
      - "../:/source"
