name: "Setup the environment"
description: "This action setup the Poetry environment and load virtual environment from cache if cache exists."
outputs:
  cache-used:
    description: "The property that defines if cache was used"
    value: "${{ steps.cached-poetry.outputs.cache-hit }}"
runs:
  using: "composite"
  steps:
    - name: "Set up Python"
      uses: "actions/setup-python@v2"
      with:
        python-version: "3.9"
    - name: "Install Poetry"
      run: "pip install poetry"
      shell: "bash"
    - name: "Cache"
      uses: "actions/cache@v2"
      id: "cached-poetry"
      with:
        path: "~/.cache/pypoetry/virtualenvs/"
        key: "{{ runner.os }}-poetry-${{ hashFiles('./poetry.lock') }}-1"
    - name: "Install evnironment"
      shell: "bash"
      run: "echo Starting..."
    - name: "Install evnironment"
      shell: "bash"
      run: "if [[ ${{ steps.cached-poetry.outputs.cache-hit }} != 'true' ]]; then poetry install; fi"
