# Generated by Django 3.1.12 on 2021-08-14 02:29

from django.db import migrations, models
import nautobot_chatops.models


class Migration(migrations.Migration):

    dependencies = [
        ("nautobot_chatops", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="commandlog",
            name="params1",
            field=models.JSONField(default=list),
        ),
    ]
