# Generated by Django 3.2.15 on 2023-07-10 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nautobot_chatops', '0005_grafana'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandlog',
            name='system_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='command_log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ChatOpsAccountLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('platform', models.CharField(max_length=32)),
                ('user_id', models.CharField(max_length=255)),
                ('nautobot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatops_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ChatOps Account Link',
                'unique_together': {('user_id', 'platform')},
            },
        ),
    ]
